# Generated by Django 2.1.5 on 2019-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0002_auto_20190124_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_test', models.CharField(max_length=200)),
            ],
        ),
    ]
